---
- name: Pull Docker image of project
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull server image
      docker_image:
        name: manan3/spe_main_project_server:latest
        source: pull
    - name: Pull client image
      docker_image:
        name: manan3/spe_main_project_client:latest
        source: pull
    - name: Create new directory
      shell: mkdir -p ~/spe_main_project_ansible
    - name: Copy Docker Compose
      copy:
        src: /usr/bin/jenkins/workspace/SPE-Endterm Project/docker-compose.yml
        dest: ~/spe_main_project_ansible/docker-compose.yml
    - name: Stop docker compose
      command: docker compose down
      args:
        chdir: ~/spe_main_project_ansible
    - name: Remove old images 
      shell: docker image rm manan3/spe_main_project_server manan3/spe_main_project_client
    - name: Run docker compose
      command: docker compose up -d
      args:
        chdir: ~/spe_main_project_ansible
